/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import codefest.Codefest;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import logic.saveBean;

/**
 *
 * @author CHAMOD
 */
public class MainDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form MainDashBoard
     */
    public MainDashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reports = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        live_Report = new javax.swing.JButton();
        saveCsvFile = new javax.swing.JButton();
        start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        reports.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reports.setText("Report");
        reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsActionPerformed(evt);
            }
        });
        getContentPane().add(reports);
        reports.setBounds(280, 380, 210, 40);

        jButton1.setText("Performance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 440, 210, 40);

        live_Report.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        live_Report.setText("Data Filter");
        live_Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                live_ReportActionPerformed(evt);
            }
        });
        getContentPane().add(live_Report);
        live_Report.setBounds(280, 260, 210, 40);

        saveCsvFile.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saveCsvFile.setText("Save CSV file");
        saveCsvFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCsvFileActionPerformed(evt);
            }
        });
        getContentPane().add(saveCsvFile);
        saveCsvFile.setBounds(280, 320, 210, 40);

        start.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        start.setText("Start the Machine / Live Data");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        getContentPane().add(start);
        start.setBounds(180, 190, 420, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaces/b1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, 10, 850, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        Live l=new Live();
        l.setVisible(true);
    }//GEN-LAST:event_startActionPerformed

    private void reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsActionPerformed
        printReport r = new printReport();
        r.setVisible(true);
    }//GEN-LAST:event_reportsActionPerformed

    private void live_ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_live_ReportActionPerformed
         viewdatabse r = new viewdatabse();
         r.setVisible(true);
    }//GEN-LAST:event_live_ReportActionPerformed

    private void saveCsvFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCsvFileActionPerformed
        csvfile r = new csvfile();
         r.setVisible(true);
    }//GEN-LAST:event_saveCsvFileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        viewpresentage m=new viewpresentage();
        m.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton live_Report;
    private javax.swing.JButton reports;
    private javax.swing.JButton saveCsvFile;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
